"""
make_official_materials.py: build the official Tinkers' Construct 3.12.1.231 reference table used by
local-tests/unit/slimeknights/tconstruct/library/materials/MaterialsParityTest.java.

Created 2026-09-29 by the parity/materials stream. The FML test must not depend on a checkout outside
the repository, so this script condenses the official generated JSON into one committed file:

  * every official material definition: craftable, hidden, tier, sortOrder, whether it is conditional,
    or its redirect targets when the definition is only a redirect
  * the stat type IDs each official material has (values are balance data and are not compared)
  * the default and per-stat traits of each official material, as "modifier@level" in file order
  * the official amounts of the venom, venombone and slimeskin recipes the materials stream owns

Usage (official reference is the shallow clone of tag v3.12.1.231, commit a5a0324954f7):
  python make_official_materials.py D:/MC/tinkers-parity/reference/TinkersConstruct-v3.12.1.231 official-materials-v3.12.1.231.json
"""
import json
import os
import sys

# Official recipe IDs (1.20.1 "recipes" folder) whose amounts the FML test compares with the port.
RECIPES = [
    "smeltery/melting/venom/eye",
    "smeltery/melting/venom/fermented_eye",
    "smeltery/casting/slime/venom/bone",
    "smeltery/casting/slime/venom/bottle",
    "tools/materials/casting/venom",
    "tools/materials/melting/venom",
    "tools/materials/composite/venombone",
    "tools/materials/venom_eye",
    "tools/materials/venom_fermented",
    "tools/materials/slimeskin/composite/earth",
    "tools/materials/slimeskin/composite/sky",
    "tools/materials/slimeskin/composite/ichor",
    "tools/materials/slimeskin/composite/ender",
    "tools/materials/slimeskin/composite/earth_cleaning",
    "tools/materials/slimeskin/composite/sky_cleaning",
    "tools/materials/slimeskin/composite/ichor_cleaning",
    "tools/materials/slimeskin/composite/ender_cleaning",
]


def load(path):
    with open(path, encoding="utf-8") as handle:
        return json.load(handle)


def traits(entries):
    return [f"{entry['name']}@{entry.get('level', 1)}" for entry in entries]


def recipe_summary(data):
    """Keep only the fields the test checks, in a loader-independent shape."""
    out = {"type": data["type"]}
    fluid = data.get("fluid")
    if isinstance(fluid, dict):
        out["fluid_amount"] = fluid["amount"]
    result = data.get("result")
    if isinstance(result, dict) and "amount" in result:
        out["result_amount"] = result["amount"]
        out["result_fluid"] = result.get("fluid") or result.get("tag")
    elif isinstance(result, str):
        out["result"] = result
    for key in ("input", "output", "material", "needed", "value", "temperature", "time", "cooling_time"):
        if key in data:
            out[key] = data[key]
    return out


def main():
    official_root, target = sys.argv[1], sys.argv[2]
    data = os.path.join(official_root, "src", "generated", "resources", "data", "tconstruct")
    materials_dir = os.path.join(data, "tinkering", "materials")
    materials = {}
    redirects = {}
    for name in sorted(os.listdir(os.path.join(materials_dir, "definition"))):
        material_id = "tconstruct:" + name[:-5]
        definition = load(os.path.join(materials_dir, "definition", name))
        if "craftable" not in definition:
            redirects[material_id] = [entry["id"] for entry in definition.get("redirect", [])]
            continue
        entry = {
            "craftable": definition["craftable"],
            "hidden": definition.get("hidden", False),
            "tier": definition.get("tier", 0),
            "sortOrder": definition.get("sortOrder", 100),
            "conditional": "condition" in definition,
        }
        stats_path = os.path.join(materials_dir, "stats", name)
        entry["stats"] = sorted(load(stats_path).get("stats", {})) if os.path.exists(stats_path) else []
        traits_path = os.path.join(materials_dir, "traits", name)
        if os.path.exists(traits_path):
            trait_json = load(traits_path)
            entry["traits"] = {
                "default": traits(trait_json.get("default", [])),
                "perStat": {stat: traits(values) for stat, values in sorted(trait_json.get("perStat", {}).items())},
            }
        else:
            entry["traits"] = {"default": [], "perStat": {}}
        materials[material_id] = entry
    recipes = {}
    for recipe in RECIPES:
        recipes["tconstruct:" + recipe] = recipe_summary(load(os.path.join(data, "recipes", *recipe.split("/")) + ".json"))
    fill = load(os.path.join(data, "mantle", "fluid_transfer", "venom_bottle_fill.json"))
    output = {
        "_comment": "Generated by make_official_materials.py from official Tinkers' Construct v3.12.1.231 (a5a0324954f7) generated data. Do not edit by hand.",
        "materials": materials,
        "redirects": redirects,
        "recipes": recipes,
        "fluid_transfer": {"tconstruct:venom_bottle_fill": {"fluid_amount": fill["fluid"]["amount"], "result": fill["result"]}},
    }
    with open(target, "w", encoding="utf-8", newline="\n") as handle:
        json.dump(output, handle, indent=1, sort_keys=False)
        handle.write("\n")
    print(f"materials={len(materials)} redirects={len(redirects)} recipes={len(recipes)} -> {target}")


if __name__ == "__main__":
    main()
